### ISSUE TITLE
Last changes in pytest-django makes django-migrations-ci not compatible

### ISSUE THREAD

**Issue by insspb** [businho/django-migrations-ci#50]
The way of pytest-django config is changed, and [django-migrations-ci](https://github.com/businho/django-migrations-ci) pytest plugin detection at https://github.com/businho/django-migrations-ci/blob/bc19219611031a8967423367a345b931423fe516/django_migrations_ci/pytest_plugin.py#L33-L37 not work anymore.

Changed lines:

https://github.com/pytest-dev/pytest-django/compare/v4.6.0...v4.7.0#diff-120a0c7749b191d7a49ee491cb042bf5952a09689a31802bebc88fba3ca94c98L802-L803

**Comment by iurisilvio** [comment]
Thanks for the report @insspb! A fix was released today in version 0.9.

I added some tests to validate, but let me know if it works for you.
